name: Convert Config with Podman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Trigger manually

jobs:
  convert_config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Ensure config.bu exists
      run: |
        if [ ! -f config.bu ]; then
          echo "Error: config.bu file not found!"
          exit 1
        fi

    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: List files for debugging
      run: ls -al

    - name: Run Podman command
      run: |
        podman run --interactive --rm quay.io/coreos/butane:release \
          --pretty --strict < config.bu > transpiled_config.ign

    - name: Upload transpiled_config.ign as artifact
      uses: actions/upload-artifact@v4
      with:
        name: transpiled-config
        path: transpiled_config.ign
