name: Convert Config with Podman

on:
  push:
    branches:
      - main
    paths:
      - config.bu
  pull_request:
    branches:
      - main
    paths:
      - config.bu
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert_config:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Podman packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-podman
          restore-keys: |
            ${{ runner.os }}-apt-podman

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Cache Butane container image
        uses: actions/cache@v4
        with:
          path: ~/.local/share/containers
          key: ${{ runner.os }}-butane-image
          restore-keys: |
            ${{ runner.os }}-butane-image

      - name: Pre-pull Butane image
        run: podman pull quay.io/coreos/butane:release

      - name: Convert config.bu to config.ign
        run: podman run --interactive --rm quay.io/coreos/butane:release --pretty --strict < config.bu > config.ign

      - uses: actions/upload-artifact@v4
        with:
          name: config
          path: config.ign

  release:
    needs: convert_config
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: config

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Automated Release"
          body: "Automated release for commit ${{ github.sha }}"
          files: config.ign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
